[workspace]
resolver = "2"

members = [
    "stub",
    "pio",
    "linux-bootloader",
]

default-members = [
    "stub"
]

[workspace.package]
version = "1.0.0"
edition = "2024"

[profile.release]
opt-level = "s"
lto = true
