[package]
name = "lzbt-systemd"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base32ct = { version = "0.2.0", features = ["alloc"] }
stderrlog = "0.5.4"
log = { version = "0.4.20", features = ["std"] }
clap = { version = "4.4.8", features = ["derive"] }
lanzaboote_tool = { path = "../shared" }
indoc = "2.0.4"
serde_json = "1.0.108"
sha2 = "0.10.8"
tempfile = "3.8.1"
nix = { version = "0.27.1", default-features = false, features = [ "fs" ] }

[dev-dependencies]
assert_cmd = "2.0.12"
expect-test = "1.4.1"
filetime = "0.2.22"
rand = "0.8.5"
goblin = "0.7.1"
walkdir = "2.4.0"
