[book]
src = "docs"

[output.html]
git-repository-url = "https://github.com/nix-community/lanzaboote"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://github.com/nix-community/lanzaboote/edit/master/{path}"
