[workspace]
resolver = "2"

members = [
    "shared",
    "systemd",
    "refind",
]

default-members = [
    "shared",
    "systemd",
    "refind"
]

[workspace.package]
version = "0.4.2"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
